from cgitb import text
import time
срать = input("Ты хочешь срать?/n")
hack = "yes"
if срать == "Да" "да":
    print("Вы удачно посрёте через 10 секунд")
    time.sleep(1)
    print("Вы удачно посрёте через 9 секунд")
    time.sleep(1)
    print("Вы удачно посрёте через 8 секунд")
    time.sleep(1)
    print("Вы удачно посрёте через 7 секунд")
    time.sleep(1)
    print("Вы удачно посрёте через 6 секунд")
    time.sleep(1)
    print("Вы удачно посрёте через 5 секунд")
    time.sleep(1)
    print("Вы удачно посрёте через 4 секунд")
    time.sleep(1)
    print("Вы удачно посрёте через 3 секунд")
    time.sleep(1)
    print("Вы удачно посрёте через 2 секунд")
    time.sleep(1)
    print("Вы удачно посрёте через 1 секунд")
    time.sleep(1)
    print("Загрузка...")
    time.sleep(1)
    print("Hack zhopa started")
    time.sleep(1)
    print("10%")
    time.sleep(1)
    print("20%")
    time.sleep(1)
    print("30%")
    time.sleep(1)
    print("40%")
    print("50%")
    print("60%")
    print("70%")
    print("80%")
    print("90%")
    time.sleep(1)
    print("100%")
    print("\033[32m {You've been hacked}" .format(text))